<?php
$site_version = '0.4';
$site_title = 'Area Critica Generale';
$site_description = 'Piccolo strumento per stampare le etichette delle pompe siringhe in modo sicuro, facile e veloce!';
$site_author = 'Pietro Isotti';
$site_image = 'assets/images/header.jpg';
$log = 'true';

$saggezza = array
        (
          '0' => "Non rinunciare ai tuoi sogni, continua a dormire.",
          '1' => "Le opportunità passano volando, per questo bisogna saltare sempre.",
          '2' => "Se la montagna viene a te... è che sta cadendo una frana!",
          '3' => 'Non è bello ciò che è bello, figuriamoci ciò che è brutto.',
          '4' => 'Chi la fa, l’aspetti. Chi non la fa, si purghi.',
          '5' => 'Non rimandare a domani quello che puoi rimandare a dopodomani.',
          '6' => 'Una mela al giorno… fanno 365 mele all’anno.',
          '7' => 'Ci sono momenti in cui va bene tutto; non ti spaventare, non dura.',
          '8' => 'Se vai a lavorare canticchiando felice hai 3 possibilità: sei miliardario, ti droghi o sei uno dei sette nani.',
      );

?>
